### ISSUE TITLE
Sidebar - laden / speichern

### ISSUE THREAD

**Issue by BoboTheBarbar** [DLVC-Project/MonoRepo#1]
Spontaner versuch mit einer Sidebar mit **zwei Punkten** zu starten: 
- Spieler anlegen 
- Spieler laden

**Comment by BoboTheBarbar** [comment]
Etwas in der Art wäre am Ende schön, ist aber etwas aufwändiger:



![Image](https://user-images.githubusercontent.com/72159062/195674468-ba414d4e-be37-48fa-be68-c25578901850.png)

https://tailwindui.com/components/application-ui/navigation/sidebar-navigation

https://getbootstrap.com/docs/5.0/examples/sidebars/#

**Comment by novawarpN7** [comment]
Geschlossen wegen Überschneidung mit #6

**Comment by BoboTheBarbar** [comment]
Bzw. Überschneidung mit #9
