### ISSUE TITLE
Teronaster Gesichtsbuch - Ja / Nein?

### ISSUE THREAD

**Issue by BoboTheBarbar** [DLVC-Project/MonoRepo#4]
Wenn es man eh Gruppen speichert (also Charaktere die mit anderen Charakteren Abenteuer erlebt haben), dann ist der Schritt von einem Social Contacts Tree nicht mehr weit.

Ich habe in DLVC Freude daran gehabt zu wissen wann einer meiner Charaktere schonmal mit einem anderen meiner Gruppe in welchem Abenteuer gespielt hat.

So kann man den Start des Abenteuers bereits eine gewisse Verbundenheit miteinander haben und den ein oder anderen Dialog anders handeln.
Ich glaube an einen richtigen Value in einem solchen Feature ;-)

**Comment by BoboTheBarbar** [comment]
@novawarpN7 @lordtulek 
Ist verständlich was ich meine? Hat jemand eine andere Meinung dazu?

**Comment by lordtulek** [comment]
Ich finde das auch spannend und hatte es immer mal wieder versucht. Wenn es also nicht zu viel Arbeit ist :)

Den Namen finde ich übrigens äußerst gut! Es heißt aber "Teronaster" mit nur einem R.

**Comment by BoboTheBarbar** [comment]
Alles klar, dann wird es als Feature für v0.2.0 auftauchen.
Gespräch ist gelocked. Feature wird in #5 umgesetzt.
