### ISSUE TITLE
UI design: Startseite

### ISSUE THREAD

**Issue by novawarpN7** [DLVC-Project/MonoRepo#6]
**Design für Startseite überlegen**

@lordtulek: ich habe ein paar Bilder gemalt, wie ich mir die Software-Oberfläche vorstellen könnte. Ich habe mich ein wenig auf deine Paint-Skizze für Kampf im Discord orientiert.

**Erstal nur für die Startseite:**

- [x] kannst du bitte kurz auf die Fragen eingehen, die ich im Bild gepostet habe? :) 
- [x] wenn dir noch was wichtiges einfällt, bitte ergänzen
- [x] gerne im Paint drüber malen
- [x] für die Icons: am einfachsten wäre es, wenn wir uns aus dieser Sammlung was aussuchen: https://fonts.google.com/icons (wenn du die nicht so ansprechend findest, können wir die in einer späteren Version noch ggf. ändern.)

![Image](https://user-images.githubusercontent.com/115102561/196028994-4524a977-8942-4bdc-8735-8c1827fc2220.png)

**Comment by BoboTheBarbar** [comment]
Aktuell habe ich als Ausgangspunkt sowas verwendet:
![grafik](https://user-images.githubusercontent.com/72159062/196029114-7d3c6ed9-c84c-49d0-a05e-255fe649b8ed.png)

Aber das sollte natürlich lieber gemeinsam refined werden. Innheralb der weißen Fläche kommt jetzt der Inhalt von #1.
Der erste Gedanke war, dass die Auswahl in der Kopfleiste, die Seitenleiste definiert. Also Abenteuer -> Spieler / Gruppe / ...

**Comment by lordtulek** [comment]
![image](https://user-images.githubusercontent.com/115400724/196031587-98d667a2-de87-4519-8ef8-1eaed208b207.png)
Ein Menüpunkt "Startseite" braucht man vermutl. nicht. Da gibt es doch nur die obigen Symbole anzuklicken, oder wie? 
Sonst passen die so. 

für Kampf gibt es das Symbol "Swords". Ist vermutlich klassischer. Gab sonst glaube ich noch ein "Coloured" oder so, fand ich auch lustig. 

"Spieler" würde ich vermutlich in "Taverne" wieder oder sowas umbenennen. Da geht es dann wohl um Spieler und Gruppen. Die kann man sonst auch trennen symbolisch, aber man kann es auch so lassen. 

Menüleiste oben find ich gut. Zurück-Button find ich auch gut. Theoretisch könnte man auf der "Startseite" sonst auch die vier Symbole vergrößert als Schaltflächen haben. 

Hintergrund weiß ich nicht spontan ... O.o

**Comment by BoboTheBarbar** [comment]
Taverne finde ich auch gut.
