### ISSUE TITLE
UI design: Kampf

### ISSUE THREAD

**Issue by novawarpN7** [DLVC-Project/MonoRepo#7]
**Design Kampf**

@lordtulek: bitte kommentieren und Änderungen/Wünsche einfach drauf malen.

![Image](https://user-images.githubusercontent.com/115102561/196028555-b7638354-9c19-4094-8728-39596a417d46.png)

**Comment by lordtulek** [comment]
![Unbenannt](https://user-images.githubusercontent.com/115400724/196029911-4a6759d0-57d2-4a49-9eb9-7884473625e5.png)

"Daneben" ist zwar eine Trefferzone, aber eine wo man ja nix machen muss. Da die Leute ja gerne selber würfeln kann das bei den Spielern dann weg. Auch habe ich da jetzt nicht verstanden, wer eigentlich wen angreift und trifft. Werden die dann angeklickt? Dann kann man das so machen. Im Sinne von "klick auf Gorgo, dann klick auf Monster" = "Gorgo greift Monster an". Schneller ist es aber vermutlich ohne das klicken. 
Und kA ob man beim Gegner auch EXP schon dazu schreiben sollte. Und kann man weitere Gegner adden? Und wo wird dann der Schaden angezeigt? Direkt daneben? 
Ich hatte jetzt mal von der Anordnung das umgestellt mit dem Monster. Wäre aber auch so bei verschiedenen Gegnertypen schwierig vermutlich.

**Comment by lordtulek** [comment]
PS: Das Symbol der Sikh als Kampfsymbol genommen ;D
