### ISSUE TITLE
UI design: Händler

### ISSUE THREAD

**Issue by novawarpN7** [DLVC-Project/MonoRepo#8]
**UI Design - Händler**

@lordtulek: bitte kommentieren und Änderungen/Wünsche einfach drauf malen.

![Image](https://user-images.githubusercontent.com/115102561/196028557-e3103ffb-ded1-44a5-81ce-1aacfc14df8c.png)

**Comment by lordtulek** [comment]
Find ich gut! :)

**Comment by novawarpN7** [comment]
@BoboTheBarbar vielleicht kannst du hier den Aufwand schätzen, und die Händler ggf. in den nächsten Meilenstein übertragen. Ich weiß nicht, ob das schon in die erste Version soll.

**Comment by novawarpN7** [comment]
> Find ich gut! :)

Decken denn Waffen, Rüstungen und Sonstiges bereits alles, was wir bei den Händlern kaufen können? Oder wie würdest du die Kategorien hier benennen, @lordtulek ?

**Comment by BoboTheBarbar** [comment]
@novawarpN7 
Aufwand ist potentiell groß. 
Die große Herausforderung besteht darin eine Daten-Architektur zu finden. Dazu sollten wir vielleicht vorher mal live ein Brainstorming haben, falls eine einfache Lösung nicht zufriedenstellen ist.

Die Kernfrage ist wie komplex es sein soll, bzw. ob es das "wert" ist.
Hier z.B. eine sehr simple Lösung die sich schnell implementieren ließe:

## Beispiel
Alle Items sind nur Items und haben:
- Name
- Typ
- Preis
- Beschreibung

Dieser Fall ist einfach, denn ich **unterscheide nicht mehr ob es eine Rüstung oder ein Trank ist** und beim suchen wird stets nach Name gesucht (von mir aus auch nach Beschreibung) oder es kann nach Typ gefiltert werden.

Jedoch muss Hans dann natürlich alle echten Infos in die Beschreibung packen. Also 
| Name | Typ | Preis | Beschreibung |
|----------|:-------------:|------:|------:|
| Bronzerüstung | Rüstung | 500 | 20 Verteidigung<br>Ist aus Bronze</br> |
| mtl. Heiltrank | Trank | 30 |  Heilt 25 Lebenspunkte|
| feuchter Händedruck | Dienstleistung | - | Eine beliebte Belohnung am ende einer harten Quest von besonders dankbaren Questgebern |

@lordtulek: Rein Theoretisch könnte man auch die anlegbaren **Typen** in die Sidebar zur Schnellnavigation packen. Ich kann später mal einen Screenshot von der Idee posten, oder Lea zeichnet was.

**Comment by BoboTheBarbar** [comment]
Vorschlag 2

| Name | Tags | Preis | Wert | Traglast | Beschreibung |
|----------|:-------------:|------:|------:|------:|------:|
| Bronzehelm | Helm, Spezial, Gewöhnlich | 500 | 20 | 5 | <br>Ist aus Bronze</br> |
| mtl. Heiltrank | Trank | 30 | 25 | 5 | Heilt 25 Lebenspunkte|
| feuchter Händedruck | Dienstleistung | - | - | - | Eine beliebte Belohnung am ende einer harten Quest von besonders dankbaren Questgebern |

**Comment by novawarpN7** [comment]
Geschlossen - Übertragung in ein neues Issue
